name: email_manager
description: "Advanced Email Extraction & Management System - A production-ready Flutter application for systematic email data processing, secure storage, and compliant email automation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Essential UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  
  # Basic utilities that don't require much space
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true 