services:
  - type: web
    name: email-manager-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    rootDir: ./scraper-engine
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: email-manager-backend
          property: port 