services:
  - type: web
    name: email-scraper-pro
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/zahuierik/EmailBot
    branch: main
    rootDir: email-manager-web/scraper-engine
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
      - key: HOST
        value: "0.0.0.0"
    healthCheckPath: /health 